[server]
host = "localhost"
port = 8080
override = true

[logger]
level = "INFO"

# Valid values
# [FATAL, ERROR, WARN, INFO, DEBUG]

[metrics]
load_average = true
cpu_load = false
disk_load = false
disk_info = false
network_stats = false
