name: system-monitoring tests

on:
  push:
    branches:
      - development
      - master

env:
  GO111MODULE: "on"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.20

      - name: Check out code
        uses: actions/checkout@v3

      - name: Linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20

      - name: Check out code
        uses: actions/checkout@v3

      - name: Test Load Average
        run: top -b -n1 | grep average

      - name: Test Cpu Load
        run: top -b -n1 | grep Cpu

      - name: Test Disk Load
        run: iostat -d -k | grep sda

      - name: Test Disk Info - Used Size
        run: df -mT

      - name: Test Disk Info - Used Inode
        run: df -iT

      - name: Test Network Stats - Listener Sockets
        run: sudo netstat -lntupe

      - name: Test Network Stats - TCP Connections
        run: ss -ta

      - name: Test Network Stats - UDP Connections
        run: ss -ua

      - name: Unit tests
        run: go test -race -v -count=100 -timeout=20m ./internal/...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  tests_by_makefile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20

      - name: Check out code
        uses: actions/checkout@v3

      - name: make lint
        run: make lint

      - name: make build
        run: make build

      - name: make version
        run: make version

      - name: make test
        run: make test
