name: system-monitoring tests

on:
  push:
    branches:
      - development-mac

env:
  GO111MODULE: "on"

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.20

      - name: Check out code
        uses: actions/checkout@v3

      - name: Linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2

  tests:
    runs-on: macos-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20

      - name: Check out code
        uses: actions/checkout@v3

      - name: Test Load Average
        run: top -l 1 | grep "Load Avg"

      - name: Test Cpu Load
        run: top -l 1 | grep "CPU usage"

      - name: Test Disk Load
        run: iostat -d

      - name: Test Disk Info - Used Size
        run: df -m

      - name: Test Disk Info - Used Inode
        run: df -i

      - name: Unit tests
        run: go test -race -v -count=100 -timeout=90m ./internal/...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20

      - name: Check out code
        uses: actions/checkout@v3

      - name: make Up service
        run: make up

      - name: Integration test
        run: make integration-test

      - name: make Down service
        run: make down

  tests_by_makefile:
    runs-on: macos-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20

      - name: Check out code
        uses: actions/checkout@v3

      - name: make lint
        run: make lint

      - name: make build-client
        run: make build-client

      - name: make build-server
        run: make build-server

      - name: make version
        run: make version

      - name: make test
        run: make test
